# Generated by Django 5.2.9 on 2025-12-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_incidentcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhtSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(default=2.0)),
                ('temp_max', models.FloatField(default=8.0)),
            ],
        ),
    ]
