# Generated by Django 5.2.9 on 2025-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_dhtsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('SEVERE', 'Severe')], default='WARNING', max_length=20),
        ),
    ]
